version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-demo
    environment:
      POSTGRES_USER: demo-user
      POSTGRES_PASSWORD: demo-password
      POSTGRES_DB: demo-db
    ports:
      - "5432:5432" # Exposes the database to your host machine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
